apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomizationvbnmoflnzbo
resources:
- ../../base
- virtual-service.yaml
namespace: kubeflow
commonLabels:
  app: jupyter-web-app
  kustomize.component: jupyter-web-app
configurations:
- params.yaml
