name: Build all images
on:
  push:
    branches:
      - test-build-all
      - master
      - v*-branch
    paths:
      - releasing/version/VERSION

jobs:
  push_to_registry:
    name: Build all images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run script
      run: |
        TAG=$(cat releasing/version/VERSION)
        pip install -U pip setuptools wheel
        pip install ruamel.yaml
        releasing/update-manifests-images $TAG
