name: Build & Publish JWA Docker image
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/crud-web-apps/jupyter/**
      - components/crud-web-apps/common/**
      - releasing/version/VERSION
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/crud-web-apps/jupyter/**
      - components/crud-web-apps/common/**

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to DockerHub
      if: github.event_name == 'push'
      run: echo "Hello world"

    - name: Run JWA build
      run: |
        cd components/crud-web-apps/jupyter
        export IMG=kubeflownotebookswg/jupyter-web-app
        make docker-build

    - name: Run JWA push
      if: github.event_name == 'push'
      run: echo "Hello world"

    - name: Run JWA push on Version change
      id: version
      if: github.event_name == 'push' && steps.filter.outputs.version == 'true'
      run: echo "Hello world"
